import React from "react";
import { Header } from "./components/layouts/Header/Header";
import BenchTimeLogo from "./images/BenchTimeLogo.png";

function NavigationItem({ name, link }: { name: string; link: string }) {
  return (
    <li className="mb-4">
      <a href={link} className="text-lg text-[#123456] hover:text-[#345678]">
        {name}
      </a>
    </li>
  );
}

export type LinkProps = {
  label: string;
  href: string;
  description: string;
  id: string;
};

const LINKS = [
  {
    label: "レシピコンバーター",
    href: "./converter",
    description: "レシピをCSV形式のテキストに変換できる機能です。",
    id: "converter",
  },
  {
    label: "会計管理",
    href: "./accountant",
    description: "サークルの会計管理を行う機能です。",
    id: "accountant",
  },
  {
    label: "レシピストレージ",
    href: "/recipe-storage",
    description: "レシピを保存、管理できる機能です。",
    id: "recipe-storage",
  },
  {
    label: "活動日の確認",
    href: "/activity-calendar",
    description: "サークルの活動予定をカレンダー形式で確認できる機能です。",
    id: "activity-calendar",
  },
];

function Navigation() {
  return (
    <nav className="flex flex-col bg-[#f1f1f1] p-4">
      <ul>
        {LINKS.map((link: LinkProps) => (
          <NavigationItem name={link.label} link={link.href} key={link.id} />
        ))}
      </ul>
    </nav>
  );
}

function Footer() {
  return (
    <footer className="bg-[#123456] text-white p-4 text-center">
      <p className="text-base">© 2024 Bench Time</p>
      <p className="text-sm">Instagram: @tsukubabenchtime</p>
    </footer>
  );
}

function HomeContent() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-4xl font-bold mb-8">Bench Time</h1>
      <p className="text-xl mb-8">
        Bench Timeは筑波大学のサークル「Bench
        Time」のためのWebアプリケーションです。
      </p>

      <div className="mb-32 grid text-center lg:max-w-5xl lg:w-full lg:mb-0 lg:grid-cols-3 lg:text-left">
        {LINKS.map((link: LinkProps) => (
          <a
            href={link.href}
            key={link.id}
            className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
            // target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`mb-3 text-2xl font-semibold`}>
              {link.label}{" "}
              <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
                -&gt;
              </span>
            </h2>
            <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
              {link.description}
            </p>
          </a>
        ))}
      </div>
    </main>
  );
}

function HomePage() {
  return (
    <>
      <Header links={LINKS} loginFlag={true} />
      {/* <Navigation /> */}
      <HomeContent />
      <Footer />
    </>
  );
}

export default HomePage;

// export default function Home() {
//   return (
//     <main className="flex min-h-screen flex-col items-center justify-between p-24">
//       {/* <Helmet>
//         <title>Bench Time HP</title>
//         <meta name="description" content="Generated by create next app"></meta>
//       </Helmet> */}
//       <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
//         <h1 className="mb-6">
//           <a href="./converter" className="underline hover:text-blue-500">
//             Go to Converter
//           </a>
//         </h1>
//       </div>
//     </main>
//   );
// }
