import Image from "next/image";
// import { Helmet } from "react-helmet";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      {/* <Helmet>
        <title>Bench Time HP</title>
        <meta name="description" content="Generated by create next app"></meta>
      </Helmet> */}
      <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
        <h1 className="mb-6">
          <a href="./converter" className="underline hover:text-blue-500">
            Go to Converter
          </a>
        </h1>
      </div>
    </main>
  );
}
